server {
  listen 80;
  server_name _;

  client_max_body_size 0;

  root /usr/share/nginx/html;
  index index.html;

  location /dav {
    proxy_pass http://backend:8080;
    proxy_http_version 1.1;
    client_max_body_size 0;
    proxy_request_buffering off;
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Destination $http_destination;
    proxy_set_header Depth $http_depth;
    proxy_set_header Overwrite $http_overwrite;
    proxy_set_header If $http_if;
    proxy_set_header If-Match $http_if_match;
    proxy_set_header If-None-Match $http_if_none_match;
  }

  location /api/ {
    proxy_pass http://backend:8080/api/;
    proxy_http_version 1.1;
    proxy_request_buffering off;
    proxy_read_timeout 3600s;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
